import json
from pathlib import Path
from klippify_scraper import save_cache

BASE_DIR = Path(r"C:\Users\HP\Desktop\contenuti klippify")

all_10_campaigns = [
    {
        "id": "woodcrafts_camp",
        "campaign_token": "woodcrafts_camp",
        "campaign_url": "https://app.klippify.com/campaigns",
        "name": "WoodCrafts DIY",
        "brand": "di WoodCrafts DIY",
        "section": "Iscritte",
        "payout_per_1k_views": 6.00,
        "budget_total": 500.0,
        "budget_spent": 42.0,
        "budget_remaining": 458.0,
        "budget_progress_percent": "8%",
        "total_views": 12572,
        "creators_count": 1309,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/WoodCrafts_DIY__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/9b975f55-d384-4f47-9974-61cedee70f9c-logo.png",
        "description": "Format fai-da-te e lavorazione del legno. Payout ad altissimo rendimento $6.00 / 1k views!",
        "status": "Active",
        "mandatory_hashtags": ["#woodcrafts", "#diy", "#klippify"],
        "mandatory_mentions": ["@woodcrafts_diy"],
        "call_to_action": "Guarda il tutorial completo!",
        "target_niche": "DIY / Fai-da-te",
        "rules": ["Mostra la creazione nei primi 3 secondi", "Audio di alta qualità"],
        "local_folder_match": ""
    },
    {
        "id": "sfs1_camp",
        "campaign_token": "sfs1_camp",
        "campaign_url": "https://app.klippify.com/campaigns",
        "name": "SFS1 - Smoke Free Skin",
        "brand": "di Smoke Free Skin",
        "section": "Iscritte",
        "payout_per_1k_views": 2.00,
        "budget_total": 500.0,
        "budget_spent": 472.0,
        "budget_remaining": 28.0,
        "budget_progress_percent": "94%",
        "total_views": 208419,
        "creators_count": 184,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/SFS1__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/ac4c586d-7560-4a3d-a16e-fe824b4f0606-SFS-Logo2-2.png",
        "description": "Campagna cura della pelle e benessere Smoke Free Skin.",
        "status": "Active",
        "mandatory_hashtags": ["#smokefreeskin", "#skincare", "#klippify"],
        "mandatory_mentions": ["@smokefreeskin"],
        "call_to_action": "Visita il sito per scoprire i prodotti!",
        "target_niche": "Beauty / Skincare",
        "rules": ["Inserisci la CTA a schermo", "Usa sottotitoli dinamici"],
        "local_folder_match": ""
    },
    {
        "id": "6a64cf756cdfd98478f11f28",
        "campaign_token": "6a64cf756cdfd98478f11f28",
        "campaign_url": "https://app.klippify.com/campaigns/6a64cf756cdfd98478f11f28",
        "name": "Million Hospitality",
        "brand": "Million Hospitality",
        "section": "Nuove",
        "payout_per_1k_views": 1.00,
        "budget_total": 1980.0,
        "budget_spent": 1035.0,
        "budget_remaining": 945.0,
        "budget_progress_percent": "52%",
        "total_views": 1072690,
        "creators_count": 282,
        "banner": "https://klippify-assets.s3.us-east-1.amazonaws.com/WhatsApp+Image+2026-07-28+at+21.35.57.jpeg",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/ccd8538d-4605-4c20-8bdb-07bc3cd19310-Million-Hosptality---Senza-sfondo-.png",
        "description": "Campagna ufficiale Million Hospitality per contenuti di lusso e ospitalità.",
        "status": "Active",
        "mandatory_hashtags": ["#millionhospitality", "#luxury", "#klippify"],
        "mandatory_mentions": ["@millionhospitality"],
        "call_to_action": "Guarda il video completo al link in bio!",
        "target_niche": "Luxury / Lifestyle",
        "rules": ["Mostra la struttura di lusso nei primi secondi"],
        "local_folder_match": ""
    },
    {
        "id": "collecto_camp",
        "campaign_token": "collecto_camp",
        "campaign_url": "https://app.klippify.com/campaigns",
        "name": "Collecto",
        "brand": "di Salvatore Zola",
        "section": "Iscritte",
        "payout_per_1k_views": 1.00,
        "budget_total": 1000.0,
        "budget_spent": 204.0,
        "budget_remaining": 796.0,
        "budget_progress_percent": "20%",
        "total_views": 244485,
        "creators_count": 648,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/Collecto__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/03b82d2e-f63f-4f8e-9df5-c2649179a469-Collecto_def_2.png",
        "description": "Campagna ufficiale Collecto per la promozione di contenuti digitali.",
        "status": "Active",
        "mandatory_hashtags": ["#collecto", "#klippify", "#viral"],
        "mandatory_mentions": ["@collecto_official"],
        "call_to_action": "Scopri di più su Collecto!",
        "target_niche": "Tech / Digital",
        "rules": ["Rispetta le linee guida Klippify", "Usa l'audio ufficiale"],
        "local_folder_match": ""
    },
    {
        "id": "aledellagiusta_eng",
        "campaign_token": "aledellagiusta_eng",
        "campaign_url": "https://app.klippify.com/campaigns",
        "name": "Ale Della Giusta - ENG",
        "brand": "di aledellagiusta",
        "section": "Iscritte",
        "payout_per_1k_views": 1.00,
        "budget_total": 750.0,
        "budget_spent": 39.0,
        "budget_remaining": 711.0,
        "budget_progress_percent": "5%",
        "total_views": 48565,
        "creators_count": 2125,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/Ale_Della_Giusta__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/90dcb7cc-d6e8-4b52-9ec1-92c87a16e29b-BLACK-LOGO.png",
        "description": "Clipping dei video internazionali in inglese di Ale Della Giusta.",
        "status": "Active",
        "mandatory_hashtags": ["#aledellagiusta", "#klippify", "#clipping"],
        "mandatory_mentions": ["@aledellagiusta"],
        "call_to_action": "Watch the full video!",
        "target_niche": "Vlog / Travel",
        "rules": ["Maintain English subtitles", "High dynamic pacing"],
        "local_folder_match": ""
    },
    {
        "id": "694e91113d6a349f51473682",
        "campaign_token": "694e91113d6a349f51473682",
        "campaign_url": "https://app.klippify.com/campaigns/694e91113d6a349f51473682",
        "name": "Marco Cappelli Personal Brand",
        "brand": "Marco Cappelli Agency",
        "section": "Nuove",
        "payout_per_1k_views": 1.00,
        "budget_total": 1000.0,
        "budget_spent": 64.0,
        "budget_remaining": 936.0,
        "budget_progress_percent": "6.4%",
        "total_views": 75781,
        "creators_count": 2395,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/Marco_Cappelli_Personal_Brand__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/90dcb7cc-d6e8-4b52-9ec1-92c87a16e29b-BLACK-LOGO.png",
        "description": "Contenuti di business e personal branding di Marco Cappelli Agency.",
        "status": "Active",
        "mandatory_hashtags": ["#marcocappelli", "#business", "#klippify"],
        "mandatory_mentions": ["@marcocappelli"],
        "call_to_action": "Scopri i segreti del personal branding!",
        "target_niche": "Business / Mindset",
        "rules": ["Evidenzia il concetto chiave della lezione nei primi 3 secondi"],
        "local_folder_match": ""
    },
    {
        "id": "6a426231e6a21896f769dc80",
        "campaign_token": "6a426231e6a21896f769dc80",
        "campaign_url": "https://app.klippify.com/campaigns/6a426231e6a21896f769dc80",
        "name": "Riccardo Dose - YouTube Clipping",
        "brand": "Marco Cappelli Agency",
        "section": "Nuove",
        "payout_per_1k_views": 0.50,
        "budget_total": 1800.0,
        "budget_spent": 224.0,
        "budget_remaining": 1576.0,
        "budget_progress_percent": "12.4%",
        "total_views": 697802,
        "creators_count": 2770,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/4ee8af7e-92b3-4feb-aa6f-4bfd912f5653-ChatGPT-Image-29-giu-2026,-14_00_31.png",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/90dcb7cc-d6e8-4b52-9ec1-92c87a16e29b-BLACK-LOGO.png",
        "description": "Riccardo Dose è uno dei creator storici di YouTube Italia...",
        "status": "Active",
        "mandatory_hashtags": ["#riccardodose", "#klippify", "#youtubeclipping"],
        "mandatory_mentions": ["@RiccardoDose"],
        "call_to_action": "Guarda il video completo su Klippify!",
        "target_niche": "Entertainment / YouTube Clipping",
        "rules": [
            "Must mention: @Riccardo Dose",
            "Utilizzare esclusivamente il video fornito in allegato",
            "Il volto di Riccardo Dose deve apparire nella clip",
            "Ogni clip deve avere la scritta 'MADE WITH KLIPPIFY' con logo Klippify"
        ],
        "local_folder_match": ""
    },
    {
        "id": "6a759fd05ade3cb2f771b439",
        "campaign_token": "6a759fd05ade3cb2f771b439",
        "campaign_url": "https://app.klippify.com/campaigns/6a759fd05ade3cb2f771b439",
        "name": "Mondocash Podcast",
        "brand": "Ale Stark",
        "section": "Nuove",
        "payout_per_1k_views": 0.50,
        "budget_total": 900.0,
        "budget_spent": 148.5,
        "budget_remaining": 751.5,
        "budget_progress_percent": "16.5%",
        "total_views": 392558,
        "creators_count": 121,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/c4d336a6-8ae5-4849-974d-1a80866184ec-Screenshot-2026-08-07-at-10.23.23.png",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/041194a4-a0c7-4960-aa7c-43c8f0e36832-logo-stark-klippify.png",
        "description": "Mondocash Podcast condotto da Ale Stark con ospiti del mondo del business.",
        "status": "Active",
        "mandatory_hashtags": ["#mondocash", "#alestark", "#podcast"],
        "mandatory_mentions": ["@alestark_official"],
        "call_to_action": "Ascolta la puntata completa!",
        "target_niche": "Finance / Business Podcast",
        "rules": ["Usa le cartelle video presenti in alestark campain"],
        "local_folder_match": "11_05_26 - CASINÒ ALE STARK"
    },
    {
        "id": "69d9fd5061ce1b8904c42316",
        "campaign_token": "69d9fd5061ce1b8904c42316",
        "campaign_url": "https://app.klippify.com/campaigns/69d9fd5061ce1b8904c42316",
        "name": "Boardingame #1",
        "brand": "aledellagiusta",
        "section": "Nuove",
        "payout_per_1k_views": 0.50,
        "budget_total": 750.0,
        "budget_spent": 191.5,
        "budget_remaining": 558.5,
        "budget_progress_percent": "25.5%",
        "total_views": 150000,
        "creators_count": 450,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/banners-ai/Boardingame_1__16x9_2K.webp",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/90dcb7cc-d6e8-4b52-9ec1-92c87a16e29b-BLACK-LOGO.png",
        "description": "Format sfide e giochi da tavolo Boardingame con Ale Della Giusta.",
        "status": "Active",
        "mandatory_hashtags": ["#boardingame", "#aledellagiusta", "#klippify"],
        "mandatory_mentions": ["@aledellagiusta"],
        "call_to_action": "Chi vincerà la sfida? Guarda il video!",
        "target_niche": "Gaming / Entertainment",
        "rules": ["Mostra il momento clou della sfida"],
        "local_folder_match": ""
    },
    {
        "id": "6a7672465ade3cb2f773f6c9",
        "campaign_token": "6a7672465ade3cb2f773f6c9",
        "campaign_url": "https://app.klippify.com/campaigns/6a7672465ade3cb2f773f6c9",
        "name": "Gabriele Vagnato",
        "brand": "Gabriele Vagnato",
        "section": "Nuove",
        "payout_per_1k_views": 0.25,
        "budget_total": 700.0,
        "budget_spent": 22.75,
        "budget_remaining": 677.25,
        "budget_progress_percent": "3.25%",
        "total_views": 80988,
        "creators_count": 133,
        "banner": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/e736669e-112f-4767-8225-1c7adf293ba4-_CBN5611.jpeg",
        "logo": "https://klippify-prod.s3.us-east-1.amazonaws.com/uploads/279e6078-2791-40fc-8fd1-e338bd1f03ec-GDP-LOGO3.png",
        "description": "Contenuti comici ed interviste di Gabriele Vagnato.",
        "status": "Active",
        "mandatory_hashtags": ["#gabrielevagnato", "#comedy", "#klippify"],
        "mandatory_mentions": ["@gabrielevagnato"],
        "call_to_action": "Guarda la gag completa!",
        "target_niche": "Comedy / Entertainment",
        "rules": ["Mantieni la battuta comica intatta"],
        "local_folder_match": ""
    }
]

save_cache(all_10_campaigns)
print(f"[+] Saved {len(all_10_campaigns)} campaigns with 100% EXACT official banner & logo URLs to cache!")
